---

- name: Install Cloudera Manager Agents
  yum:
    name:
    - cloudera-manager-daemons
    - cloudera-manager-agent
    update_cache: yes
    state: installed

- name: Configure Cloudera Manager Agent 'server_host'
  lineinfile:
    dest: /etc/cloudera-scm-agent/config.ini
    regexp: "^server_host"
    line: "server_host={{ groups['scm_server'][0] }}"

- name: Restart Cloudera Manager Agents
  service:
    name: cloudera-scm-agent
    state: restarted
    enabled: yes
